tags:
  - name: auth
    description: Authentication API

paths:
  # [POST] auth/register
  /auth/register:
    post:
      tags:
        - auth
      summary: Register New User
      parameters:
        - name: body
          in: body
          description: User Registration Data
          required: true
          schema:
            $ref: '#/definitions/userRegistration'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict - Email already exists'
        500:
          description: 'Server Error'

  # [POST] auth/login
  /auth/login:
    post:
      tags:
        - auth
      summary: User Login
      parameters:
        - name: body
          in: body
          description: User Login Data
          required: true
          schema:
            $ref: '#/definitions/userLogin'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        401:
          description: 'Wrong credentials'
        500:
          description: 'Server Error'

# definitions
definitions:
  userRegistration:
    type: object
    required:
      - email
      - password
      - first_name
      - last_name
    properties:
      email:
        type: string
        description: User Email
        example: user@example.com
      password:
        type: string
        description: User Password (6-20 characters)
        example: password123
      first_name:
        type: string
        description: User First Name (2-50 characters, letters only)
        example: John
      last_name:
        type: string
        description: User Last Name (2-50 characters, letters only)
        example: Doe

  userLogin:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: User Email
        example: user@example.com
      password:
        type: string
        description: User Password
        example: password123

schemes:
  - https
  - http
